---
title: "Age, Time, and Cohorts in Package 'dembase'"
author: "John Bryant"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Age, Time, and Cohort in Package 'dembase'}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Everything denominated in years

## Labelling intervals


| Lower limit `l`, upper limit `u` | Age label             | Time label |
|:---------------------------------|:---------------------:|:----------:|	
| `l` is integer and `u=l+1`       | "l"                   | "l" or "u" |
| `l`, `u` both integer            | "l-U" where `U = u-1` | "l-u"      |
| `l`, `u` define month            | "l-u"                 | "Y-m"      |
| `l`, `u` define quarter          | "l-u"                 | "Y-Q"      |
| `l` and/or `u` non-integer       | "l-u"                 | "l-u"      |
| `l` is -Inf, `u` finite          | "<u"                  | "<u"       |
| `l` is finite, `u` is            | "l+"                  | "l+"       |
-------------------------------------------------------------------------

But also understands "L-u" where `L=l+1`.

## Labelling points



### Age intervals

- [a, a+1), a is integer: "a"
- [a, a+n), a, n is integer: "a-b", where b = a+n-1
- [a, a+n), a and/or n is non-integer: "a-b", where b = a+n
- (-Inf, a), "<a"
- ([a, Inf), "a+"

### Time intervals



## Cleaning data

cleanAgeGroup(age)
cleanPeriod(period)


## Creating labels from dates

dateToAgeGroup(date, dob, breaks, firstOpen = TRUE, lastOpen = TRUE)
dateToCohort(date, breaks, firstOpen = TRUE, lastOpen = FALSE)
dateToPeriod(date, breaks, firstOpen = FALSE, lastOpen = FALSE)
dateToTriangle(date, dob, breaks, firstOpen = TRUE, lastOpen = FALSE)


## Creating labels from years

ageToAgeGroup(age, breaks = seq(0, 100, 5), firstOpen = FALSE, lastOpen = TRUE) 
yearToPeriod(year, breaks, firstOpen = FALSE, lastOpen = FALSE)



## subarray

```
subarray(time > 2010)
subarray(time > "2010")
```

## Counts, accounts

Movements(population, births = NULL, internal = NULL, entries = list(), 
    exits = list(), net = list(), labelStart = TRUE)

Counts(object, dimtypes = NULL, dimscales = NULL, type = NULL)

exposure((object, triangles = FALSE, labelStart = TRUE)



